//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT 
        ///          c.id AS ClientId, 
        ///          c.first_name AS FirstName, 
        ///          c.last_name AS LastName
        ///      FROM 
        ///          clients c
        ///      JOIN 
        ///          subscriptions s ON c.id = s.client_id
        ///      WHERE 
        ///          s.visits &gt; @MinVisitCount
        ///      GROUP BY 
        ///          c.id, c.first_name, c.last_name
        ///      ORDER BY 
        ///          c.last_name, c.first_name;
        ///    .
        /// </summary>
        internal static string GetClientsWithSubscriptionsAboveVisitCount {
            get {
                return ResourceManager.GetString("GetClientsWithSubscriptionsAboveVisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT
        ///          DATE_TRUNC(&apos;month&apos;, CreatedDate) AS Month,
        ///          COUNT(id) AS NewClientCount
        ///      FROM
        ///          clients
        ///      GROUP BY
        ///          Month
        ///      ORDER BY
        ///          Month DESC;
        ///    .
        /// </summary>
        internal static string GetNewClientsByMonth {
            get {
                return ResourceManager.GetString("GetNewClientsByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT
        ///          t.Id AS TrainerId,
        ///          t.occupied_places AS OccupiedPlaces
        ///      FROM
        ///          trainers t
        ///      WHERE
        ///          t.occupied_places &gt; @Threshold
        ///      ORDER BY 
        ///          t.occupied_places DESC;
        ///    .
        /// </summary>
        internal static string GetPopularTrainersWithOccupiedPlaces {
            get {
                return ResourceManager.GetString("GetPopularTrainersWithOccupiedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT 
        ///          t.id AS TrainerId, 
        ///          COUNT(s.id) AS SubscriptionCount
        ///      FROM 
        ///          subscriptions s
        ///      JOIN 
        ///          trainers t ON s.trainer_id = t.id
        ///      GROUP BY 
        ///          t.id
        ///      ORDER BY 
        ///          SubscriptionCount DESC;
        ///    .
        /// </summary>
        internal static string GetSubscriptionCountByTrainer {
            get {
                return ResourceManager.GetString("GetSubscriptionCountByTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT 
        ///          t.id AS TrainerId, 
        ///          t.name AS TrainerName,
        ///          COALESCE(SUM(s.price), 0) AS TotalIncome
        ///      FROM 
        ///          trainers t
        ///      LEFT JOIN 
        ///          subscriptions s ON t.id = s.trainer_id
        ///      GROUP BY 
        ///          t.id, t.name
        ///      ORDER BY 
        ///          TotalIncome DESC;
        ///    .
        /// </summary>
        internal static string GetTotalIncomeByTrainer {
            get {
                return ResourceManager.GetString("GetTotalIncomeByTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT 
        ///          c.id AS ClientId, 
        ///          c.first_name AS FirstName, 
        ///          c.last_name AS LastName,
        ///          COUNT(v.id) AS VisitCount
        ///      FROM 
        ///          clients c
        ///      LEFT JOIN 
        ///          visits v ON c.id = v.client_id
        ///      GROUP BY 
        ///          c.id, c.first_name, c.last_name
        ///      ORDER BY 
        ///          VisitCount DESC;
        ///    .
        /// </summary>
        internal static string GetVisitsCountByClient {
            get {
                return ResourceManager.GetString("GetVisitsCountByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      INSERT INTO Clients (Id, DateOfBirth, Gender, PassportId, ExternalClientId)
        ///      VALUES (@Id, @DateOfBirth, @Gender, @PassportId, @ExternalClientId)
        ///      ON CONFLICT (Id) DO UPDATE
        ///      SET DateOfBirth = EXCLUDED.DateOfBirth,
        ///          Gender = EXCLUDED.Gender,
        ///          PassportId = EXCLUDED.PassportId,
        ///          ExternalClientId = EXCLUDED.ExternalClientId;
        ///    .
        /// </summary>
        internal static string UpsertClientProfile {
            get {
                return ResourceManager.GetString("UpsertClientProfile", resourceCulture);
            }
        }
    }
}
